### ISSUE TITLE
Panic with Healthcheck (as CRD) with labels in metadata

### ISSUE THREAD

**Issue by fcastarede** [mcorbin/cabourotte#22]
Hi,

With Cabourotte version 1.1.0, labels in Healthcheck manifest triggers panic : 

```yaml
apiVersion: cabourotte.mcorbin.fr/v1
kind: Healthcheck
metadata:
  labels:
    instance: mysite
  name: mysite-healthcheck
  namespace: mynamespace
spec:
  http-checks:
  - insecure: false
    interval: 10s
    name: mysite-http-check
    path: /
    port: 443
    protocol: https
    redirect: true
    target: www.mysite.tld
    timeout: 10s
    valid-status:
    - 200
    - 201
```

```log
{"level":"info","ts":1646420906.560082,"caller":"kubernetes/crd.go:109","msg":"Reconciling healthcheck CRD mysite-healthcheck"}
--
2022-03-04 20:08:26 | panic: assignment to entry in nil map
2022-03-04 20:08:26 |  
2022-03-04 20:08:26 | goroutine 787 [running]:
2022-03-04 20:08:26 | github.com/mcorbin/cabourotte/healthcheck.MergeLabels(0xc0004c3940, 0xc0001c8030)
2022-03-04 20:08:26 | /app/healthcheck/root.go:230 +0xb0
2022-03-04 20:08:26 | github.com/mcorbin/cabourotte/discovery/kubernetes.(*HealthcheckReconciler).reconcileCRDs(0xc0005d7200, 0xc0001ce000)
2022-03-04 20:08:26 | /app/discovery/kubernetes/crd.go:129 +0xb85
2022-03-04 20:08:26 | github.com/mcorbin/cabourotte/discovery/kubernetes.(*HealthcheckReconciler).Reconcile(0xc0005d7200, {0x193f6b8, 0xc0000e4270}, {{{0x2567358, 0x162f040}, {0xc00009c048, 0x30}}})
2022-03-04 20:08:26 | /app/discovery/kubernetes/crd.go:154 +0x12c
2022-03-04 20:08:26 | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000150d10, {0x193f6b8, 0xc0000e41b0}, {{{0xc0006c3338, 0x162f040}, {0xc0002d54d0, 0x413974}}})
2022-03-04 20:08:26 | /app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114 +0x26f
2022-03-04 20:08:26 | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000150d10, {0x193f610, 0xc000391780}, {0x157d600, 0xc000049b20})
2022-03-04 20:08:26 | /app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311 +0x33e
2022-03-04 20:08:26 | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000150d10, {0x193f610, 0xc000391780})
2022-03-04 20:08:26 | /app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266 +0x205
2022-03-04 20:08:26 | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
2022-03-04 20:08:26 | /app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227 +0x85
2022-03-04 20:08:26 | created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
2022-03-04 20:08:26 | /app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:223 +0x357
```

If I remove labels in metadata it works.

**Comment by mcorbin** [comment]
Hello,

Thank you for your report.
I found the issue, I will prepare a fix and do a release soon.

**Comment by mcorbin** [comment]
The latest release (v1.2.0) should fix the issue (I also tested it on a Kubernetes cluster)
Can you please tell me if it's OK for you ?

**Comment by fcastarede** [comment]
It works neat with the latest release v1.2.0.

Thanks a lot for your work on Cabourotte, and largely for your share through your blog.
